api-key: ""
auth: []
cainfo: ""
capath: ""
direct-domains: []
dns: []
fast-fail-regexps: []
log-stats: 0
logfile: ""
max-logsize: 0
status-address: "localhost:0"
no-autodetect: false
no-proxy-caching: false
tunnel-pool: false
no-ssl-bump-domains: []
pac: ""
pidfile: ""
proxy: ""
proxy-tunnel: true
proxy-userpwd: ""
readyfile: ""
region: "us-west"
rest-url: ""
scproxy-port: 0
scproxy-read-limit: 0
scproxy-write-limit: 0
se-port: 0
shared-tunnel: false
tunnel-domains: []
tunnel-name: "nightly-tests-tunnel"
user: ""
verbose: 0