name: Tests for PR/Check-ins

on:
  # push:
  #   branches:
  #     - main
  pull_request:
    branches:
      - main

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install npm
        run: npm install

      - name: unit test
        run: npm run test:unit

  sfc-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install npm
        run: npm install

      - name: e2e test
        run: npm run test:sfc

  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install npm
        run: npm install

      - name: e2e test
        run: npm run test:e2e

  type-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install npm
        run: npm install

      - name: e2e test
        run: npm run test:types
