name: Continuous Integration Tests

on:
  schedule:
    # - cron "0 0 * * *"
    - cron: "*/5 * * * *"
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
  SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install npm
        run: npm install

      - name: test unit-test
      - run: npm run test:unit
