name: Continuous Integration Tests

on:
  schedule:
    # - cron "0 0 * * *"
    - cron: "*/5 * * * *"
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
  SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}

jobs:
  unit-test:
    runs-on: ubuntu-latest
  steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
       run: |
          npm install
      - name: Run unit tests
        run: |
          npm run test:unit
