apiVersion: v1
kind: cypress
defaults: {}
showConsoleLog: false
sauce:
  region: us-west-1
  concurrency: 10
  sauceignore: .sauceignore
cypress:
  configFile: cypress.config.ts
  version: 13.3.0
  record: false
  key: ""
  reporters: []
tunnel-name: github-action-tunnel
suites:
- name: cypress - macos 11.00 - chrome
  browser: chrome
  platformName: "macOS 11.00"
  config:
    testingType: e2e
    specPattern:
    - '**/*.*'
rootDir: .
artifacts:
  download:
    match:
    - '*'
    when: fail
    directory: ./artifacts
