apiVersion: v1
kind: cypress
sauce:
  region: us-west-1
  concurrency: 10 # Controls how many suites are executed at the same time.
  metadata:
    tags:
      - e2e
      - release team
      - other tag
    build: Github Run $GITHUB_RUN_ID
  tunnel:
    name: oauth-allison-140ee_tunnel_name
    owner: oauth-allison-140ee
cypress:
  version: 12.17.2 # See https://docs.saucelabs.com/web-apps/automated-testing/cypress/#supported-testing-platforms for a list of supported versions.
  configFile: "cypress.config.ts"
rootDir: ./
suites:
  - name: "Chrome on Windows"
    browser: "chrome"
    platformName: "Windows 11"
    config:
      specPattern: [ "test/unit/**/*.*" ] 
  # - name: "Chrome Beta on Windows 11"
  #   browser: "chrome"
  #   browserVersion: 'beta'
  #   platformName: "Windows 11"
  #   config:
  #     specPattern: [ "cypress/e2e/*.*" ] 
  # - name: "Chrome Dev on Windows 11"
  #   browser: "chrome"
  #   browserVersion: 'dev'
  #   platformName: "Windows 11"
  #   config:
  #     specPattern: [ "cypress/e2e/*.*" ] 
  # - name: "Edge on Windows 11"
  #   browser: "microsoftedge"
  #   browserVersion: '113'
  #   platformName: "Windows 11"
  #   config:
  #     specPattern: [ "cypress/e2e/*.*" ] 
  # - name: "Edge dev on Windows 11"
  #   browser: "microsoftedge"
  #   browserVersion: 'dev'
  #   platformName: "Windows 11"
  #   config:
  #     specPattern: [ "cypress/e2e/*.*" ] 
  # - name: "Firefox on Mac"
  #   browser: "firefox"
  #   browserVersion: "104"
  #   shard: spec
  #   platformName: "macOS 12"
  #   config:
  #     specPattern: [ "cypress/e2e/**/*.*" ]
